DELETE http://localhost:8080/events/7
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NDAwMjczMDIsInVzZXJJZCI6Mn0.vSV_WvzQkCi9EEd6lEkzHudJxttVXJsqqjD6ZJX0Jkw
